import React from 'react';
import { Send, Target } from 'feather-icons-react';

/**
 * Export-specific columns for packages table
 * These columns are flattened for better Excel export compatibility
 */
export const exportColumns = [
  {
    title: "Order NO",
    dataIndex: "OrderNO",
  },
  {
    title: "Sender Name",
    dataIndex: "VendorName",
  },
  {
    title: "Sender Phone",
    dataIndex: "VendorPhone",
  },
  {
    title: "Receiver Name",
    dataIndex: "ReceiverContactName",
  },
  {
    title: "Receiver Phone",
    dataIndex: "ReceiverContactPhone",
  },
  {
    title: "Receiver Address",
    dataIndex: "ReceiverStreetName",
  },
  {
    title: "Receiver Building",
    dataIndex: "ReceiverBuilding",
  },
  {
    title: "Service Fee",
    dataIndex: "ServiceFee",
  },
  {
    title: "COD Amount",
    dataIndex: "CODAmount",
  },
  {
    title: "Origin DC",
    dataIndex: "OriginDCName",
  },
  {
    title: "Destination DC",
    dataIndex: "DestinationDCName",
  },
  {
    title: "Route Info",
    dataIndex: "RouteInfo",
  },
  {
    title: "First Logged DC",
    dataIndex: "InitialLogDCName",
  },
  {
    title: "Current Location",
    dataIndex: "LatestLogDCName",
  },
  {
    title: "Date Added",
    dataIndex: "DateAdded",
  },
  {
    title: "Added By",
    dataIndex: "AddedBy",
  },
  {
    title: "Status",
    dataIndex: "StatusName",
  },
  {
    title: "Rider Name",
    dataIndex: "RiderName",
  },
  {
    title: "Delivery Type",
    dataIndex: "DeliveryType",
  },
  {
    title: "Shipment Size",
    dataIndex: "ShipmentSize",
  },
  {
    title: "Sales Agent",
    dataIndex: "SalesAgent",
  },
  {
    title: "Generated By",
    dataIndex: "GeneratedBy",
  }
];

/**
 * PDF-specific columns for packages table
 * These columns combine related data for better PDF presentation
 */
export const pdfColumns = [
  {
    title: "Order NO",
    dataIndex: "OrderNO",
    sorter: (a, b) => a.OrderNO.localeCompare(b.OrderNO),
  },
  {
    title: "Sender",
    dataIndex: "VendorPhone",
    sorter: (a, b) => {
      const codeCompare = a.VendorPhone.localeCompare(b.VendorPhone);
      if (codeCompare !== 0) return codeCompare;
      return a.VendorName.localeCompare(b.VendorName);
    },
    render: (text, record) => (
      <div>
        <div>{record.VendorName}</div>
        <small className="text-muted">{record.VendorPhone}</small>
      </div>
    ),
  },
  {
    title: "Receiver",
    dataIndex: "ReceiverContactName",
    sorter: (a, b) => {
      const codeCompare = a.ReceiverContactPhone.localeCompare(b.ReceiverContactPhone);
      if (codeCompare !== 0) return codeCompare;
      return a.ReceiverContactName.localeCompare(b.ReceiverContactName);
    },
    render: (text, record) => {
      if (!record.ReceiverContactName && !record.ReceiverContactPhone) {
        return <span>-</span>;
      }
      return (
        <div style={{ maxWidth: '200px' }} className="text-truncate" title={`${record.ReceiverContactName || "-"} (${record.ReceiverStreetName || "-"}) - ${record.ReceiverContactPhone || "-"}`}>
          <div>{record.ReceiverContactName || "-"}</div>
          <small className="text-muted">{record.ReceiverContactPhone || "-"}</small>
        </div>
      );
    },
  },
  {
    title: "Amount",
    dataIndex: "ServiceFee",
    render: (text, record) => {
      // ServiceFee and CODAmount
      const serviceFee = record.ServiceFee ? parseFloat(record.ServiceFee).toFixed(2) : "0.00";
      const codAmount = record.CODAmount ? parseFloat(record.CODAmount).toFixed(2) : "0.00";
      return (
        <div>
          <div>Fee: {serviceFee}</div>
          <div>COD: {codAmount}</div>
        </div>
      );
    }
  },
  {
    title: "Route",
    dataIndex: "OriginDCCode",
    sorter: (a, b) => {
      const originCompare = a.OriginDCName.localeCompare(b.OriginDCName);
      if (originCompare !== 0) return originCompare;
      return a.DestinationDCName.localeCompare(b.DestinationDCName);
    },
    render: (text, record) => {
      const inTransit =
        record.LatestLogDCName &&
        record.LatestLogDCName !== record.DestinationDCName;
      return (
        <div>
          <div className="d-flex align-items-center mb-1">
            <Send size={14} className="text-primary me-1" />
            <span className="ms-1 fw-medium">{record.OriginDCName}</span>
          </div>
          <div className="d-flex align-items-center">
            <Target size={14} className="text-success me-1" />
            <span className="ms-1 fw-medium">{record.DestinationDCName} <span>{record.ReceiverBuilding && (<>({record.ReceiverBuilding})</>)}</span></span>
          </div>
          {inTransit && (
            <small className="text-muted">Currently at: {record.LatestLogDCName}</small>
          )}
        </div>
      );
    },
  },
  {
    title: "Date Added",
    dataIndex: "DateAdded",
    sorter: (a, b) => new Date(a.DateAdded).getTime() - new Date(b.DateAdded).getTime(),
    render: (text) => {
      if (!text) return "-";
      // Parse UTC date and convert to local time
      const utcDate = new Date(text + "Z");
      return (
        <div>
          <div>{utcDate.toLocaleDateString()}</div>
          <small className="text-muted">{utcDate.toLocaleTimeString()}</small>
        </div>
      );
    },
  },
  {
    title: "Added By",
    dataIndex: "AddedBy",
    sorter: (a, b) => (a.AddedBy || "").localeCompare(b.AddedBy || ""),
  },
  {
    title: "Status",
    dataIndex: "StatusID",
    sorter: (a, b) => (a.StatusID || 0) - (b.StatusID || 0),
    render: (text, record) => {
      const getStatusBadgeClass = (statusCode) => {
        switch (statusCode) {
          // 100 Vendor
          case 101: // VENDOR_CREATED
            return "badge bg-primary"; // blue
          case 102: // VENDOR_READY_FOR_PICKUP
            return "badge bg-info"; // cyan
          case 103: // VENDOR_HANDED_TO_DC
            return "badge bg-dark"; // dark gray

          // 200 Inbound / DC transfer
          case 201: // INBOUND_TO_DC
            return "badge bg-warning text-dark"; // amber
          case 202: // ARRIVED_AT_DC
            return "badge bg-success"; // green
          case 206: // DC_HOLD_FOR_TRANSFER
            return "badge bg-secondary"; // gray
          case 207: // DC_TRANSFER_BATCHED
            return "badge bg-light text-dark"; // white
          case 208: // DC_TRANSFER_DISPATCHED
            return "badge bg-primary"; // blue
          case 209: // DC_TRANSFER_INBOUND
            return "badge bg-info"; // cyan

          // 300 DC & QC
          case 301: // DC_QC_CHECK
            return "badge bg-warning text-dark";
          case 302: // DC_QC_PASSED
            return "badge bg-success";
          case 303: // DC_QC_FAILED
            return "badge bg-danger";
          case 304: // DC_STOCKED
            return "badge bg-dark";
          case 305: // DC_TRACKING_ASSIGNED
            return "badge bg-secondary";

          // 400 Assignment
          case 401: // ASSIGNED_TO_DELIVERY
            return "badge bg-primary";
          case 402: // ASSIGNED_FOR_PICKUP
            return "badge bg-info";
          case 403: // ASSIGNED_TO_PACK_CENTER
            return "badge bg-secondary";
          case 410: // DELIVERY_BATCHED
            return "badge bg-dark";

          // 500 Delivery
          case 501: // OUT_FOR_DELIVERY
            return "badge bg-warning text-dark";
          case 502: // DELIVERY_ATTEMPTED
            return "badge bg-info";
          case 503: // DELIVERED
            return "badge bg-success";
          case 504: // DELIVERY_WAITLIST
            return "badge bg-light text-dark";

          // 600 Pickup
          case 601: // PICKUP_READY
            return "badge bg-info";
          case 602: // PICKUP_PENDING_CUSTOMER
            return "badge bg-warning text-dark";
          case 603: // PICKED_UP
            return "badge bg-success";

          // 700 Return
          case 701: // RETURN_REQUESTED_BY_CUSTOMER
            return "badge bg-primary";
          case 702: // RETURN_IN_TRANSIT
            return "badge bg-warning text-dark";
          case 703: // RETURNED_TO_VENDOR
            return "badge bg-info";
          case 704: // RETURN_CLOSED
            return "badge bg-secondary";

          // 800 Payment
          case 801: // PAYMENT_INITIATED
            return "badge bg-info";
          case 802: // COD_COLLECTED
            return "badge bg-primary";
          case 803: // COD_REMITTED_TO_VENDOR
            return "badge bg-dark";
          case 804: // PAYMENT_CONFIRMED
            return "badge bg-success";
          case 805: // PAYMENT_FAILED
            return "badge bg-danger";

          // 900 Closed
          case 901: // CLOSED_SUCCESS
            return "badge bg-success";
          case 902: // CLOSED_CANCELLED
            return "badge bg-danger";
          case 903: // CLOSED_FAILED
            return "badge bg-dark";

          default:
            return "badge bg-secondary";
        }
      };

      return (
        <span className={getStatusBadgeClass(text)}>{record.StatusName}</span>
      );
    },
  },
  {
    title: "Rider",
    dataIndex: "RiderName",
    sorter: (a, b) => (a.RiderName || "").localeCompare(b.RiderName || ""),
    render: (text) => text || "-",
  },
  {
    title: "Sales Agent",
    dataIndex: "SalesAgent",
    sorter: (a, b) => (a.SalesAgent || "").localeCompare(b.SalesAgent || ""),
    render: (text) => text || "-",
  },
  {
    title: "Generated By",
    dataIndex: "GeneratedBy",
    sorter: (a, b) => (a.GeneratedBy || "").localeCompare(b.GeneratedBy || ""),
    render: (text) => text || "-",
  },
];
